server {
    listen 80;

    location /live {
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t                    ts;
        }
        root /usr/share/nginx/html;
        add_header Cache-Control        no-cache;
        add_header Access-Control-Allow-Origin  *;
        add_header Access-Control-Allow-Headers *;
        add_header Access-Control-Allow-Methods GET,OPTIONS;
    }


    location /vod/ {
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t                    ts;
        }
        alias /castify-vod/;
        add_header Cache-Control        max-age=3600;
        add_header Access-Control-Allow-Origin  *;
        add_header Access-Control-Allow-Headers *;
        add_header Access-Control-Allow-Methods GET,OPTIONS;
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    location / {
        return 404;
    }
}
